### PR TITLE
Update signed headers verification logic to process revocations

### PR DESCRIPTION
**Pull request by aydarng**

### CODE REVIEW

**Comment by aydarng** [comment]
Tests require verifier:dev to be using existing keri version(weboftrust/keri:1.2.0-dev13 is not available any more)

**Review by 2byrds — APPROVED** [review]
LGTM

**Comment by 2byrds** [comment]
@aydarng you will probably need to us an RC, or if the new stable release works that would be ideal

**Comment by aydarng** [comment]
> @aydarng you will probably need to us an RC, or if the new stable release works that would be ideal

Yes, I discussed it today with @ronakseth96. Let's discuss it first tomorrow, because we need to have the same versions of keri in all our projects

**Review by 2byrds — APPROVED** [review]

**Pull request merged**
